//
// Created by ebbew on 19-10-2024.
//

#ifndef ALDA_TEAM3_EBBE_ROBIN_MATHIAS_SCHEDULERCLI_H
#define ALDA_TEAM3_EBBE_ROBIN_MATHIAS_SCHEDULERCLI_H


class SchedulerCLI {

};


#endif //ALDA_TEAM3_EBBE_ROBIN_MATHIAS_SCHEDULERCLI_H
