# Use the official Ruby image
FROM ruby:3.2

# Set the working directory
WORKDIR /app

# Copy the Gemfile and Gemfile.lock into the container
COPY Gemfile Gemfile.lock /app/

# Install dependencies
RUN bundle install

# Copy the application code
COPY . /app

# Expose port 4567
EXPOSE 4567

# Start the application
CMD ["ruby", "app.rb", "-o", "0.0.0.0"]
